In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
price=pd.read_csv('train[1].csv')
price.head()

Battery_Power  Clock_Speed  FC  Int_Memory  Mobile_D  Mobile_W  Cores  PC  \
0            842          2.2   1           7       0.6       188      2   2   
1           1021          0.5   0          53       0.7       136      3   6   
2            563          0.5   2          41       0.9       145      5   6   
3            615          2.5   0          10       0.8       131      6   9   
4           1821          1.2  13          44       0.6       141      2  14   

   Pixel_H  Pixel_W  ...  Screen_H  Screen_W  Talk_Time  Four_G  Three_G  \
0       20      756  ...         9         7         19       0        0   
1      905     1988  ...        17         3          7       1        1   
2     1263     1716  ...        11         2          9       1        1   
3     1216     1786  ...        16         8         11       0        1   
4     1208     1212  ...         8         2         15       1        1   

   Touch_Screen  Dual_SIM  Bluetooth  WiFi  Price_Range  
0             0         0          0     1            1  
1             1         1          1     0            2  
2             1         1          1     0            2  
3             0         0          1     0            2  
4             1         0          1     0            1  

[5 rows x 21 columns]

In [ ]:
price.tail()

Battery_Power  Clock_Speed  FC  Int_Memory  Mobile_D  Mobile_W  Cores  \
1995            794          0.5   0           2       0.8       106      6   
1996           1965          2.6   0          39       0.2       187      4   
1997           1911          0.9   1          36       0.7       108      8   
1998           1512          0.9   4          46       0.1       145      5   
1999            510          2.0   5          45       0.9       168      6   

      PC  Pixel_H  Pixel_W  ...  Screen_H  Screen_W  Talk_Time  Four_G  \
1995  14     1222     1890  ...        13         4         19       1   
1996   3      915     1965  ...        11        10         16       0   
1997   3      868     1632  ...         9         1          5       1   
1998   5      336      670  ...        18        10         19       1   
1999  16      483      754  ...        19         4          2       1   

      Three_G  Touch_Screen  Dual_SIM  Bluetooth  WiFi  Price_Range  
1995        1             1         1          1     0            0  
1996        1             1         1          1     1            2  
1997        1             1         1          0     0            3  
1998        1             1         0          0     1            0  
1999        1             1         1          1     1            3  

[5 rows x 21 columns]

In [ ]:
price.dtypes

Battery_Power      int64
Clock_Speed      float64
FC                 int64
Int_Memory         int64
Mobile_D         float64
Mobile_W           int64
Cores              int64
PC                 int64
Pixel_H            int64
Pixel_W            int64
Ram                int64
Screen_H           int64
Screen_W           int64
Talk_Time          int64
Four_G             int64
Three_G            int64
Touch_Screen       int64
Dual_SIM           int64
Bluetooth          int64
WiFi               int64
Price_Range        int64
dtype: object

In [ ]:
price.columns

Index(['Battery_Power', 'Clock_Speed', 'FC', 'Int_Memory', 'Mobile_D',
       'Mobile_W', 'Cores', 'PC', 'Pixel_H', 'Pixel_W', 'Ram', 'Screen_H',
       'Screen_W', 'Talk_Time', 'Four_G', 'Three_G', 'Touch_Screen',
       'Dual_SIM', 'Bluetooth', 'WiFi', 'Price_Range'],
      dtype='object')

In [ ]:
price.shape

(2000, 21)

training the dataset or preparing x and y




In [ ]:
y=price['Price_Range']

In [ ]:
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: Price_Range, Length: 2000, dtype: int64

In [ ]:
x=price.drop('Price_Range',axis=1)

In [ ]:
x

Battery_Power  Clock_Speed  FC  Int_Memory  Mobile_D  Mobile_W  Cores  \
0               842          2.2   1           7       0.6       188      2   
1              1021          0.5   0          53       0.7       136      3   
2               563          0.5   2          41       0.9       145      5   
3               615          2.5   0          10       0.8       131      6   
4              1821          1.2  13          44       0.6       141      2   
...             ...          ...  ..         ...       ...       ...    ...   
1995            794          0.5   0           2       0.8       106      6   
1996           1965          2.6   0          39       0.2       187      4   
1997           1911          0.9   1          36       0.7       108      8   
1998           1512          0.9   4          46       0.1       145      5   
1999            510          2.0   5          45       0.9       168      6   

      PC  Pixel_H  Pixel_W   Ram  Screen_H  Screen_W  Talk_Time  Four_G  \
0      2       20      756  2549         9         7         19       0   
1      6      905     1988  2631        17         3          7       1   
2      6     1263     1716  2603        11         2          9       1   
3      9     1216     1786  2769        16         8         11       0   
4     14     1208     1212  1411         8         2         15       1   
...   ..      ...      ...   ...       ...       ...        ...     ...   
1995  14     1222     1890   668        13         4         19       1   
1996   3      915     1965  2032        11        10         16       0   
1997   3      868     1632  3057         9         1          5       1   
1998   5      336      670   869        18        10         19       1   
1999  16      483      754  3919        19         4          2       1   

      Three_G  Touch_Screen  Dual_SIM  Bluetooth  WiFi  
0           0             0         0          0     1  
1           1             1         1          1     0  
2           1             1         1          1     0  
3           1             0         0          1     0  
4           1             1         0          1     0  
...       ...           ...       ...        ...   ...  
1995        1             1         1          1     0  
1996        1             1         1          1     1  
1997        1             1         1          0     0  
1998        1             1         0          0     1  
1999        1             1         1          1     1  

[2000 rows x 20 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.75,random_state=0)

In [ ]:
X_train.shape

(1500, 20)

In [ ]:
X_test.shape

(500, 20)

In [ ]:
Y_train.shape

(1500,)

In [ ]:
Y_test.shape

(500,)

KNN neigbohr model is used here

In [ ]:
model_knn=KNeighborsClassifier(n_neighbors=3)

In [ ]:
model_knn=model_knn.fit(X_train,Y_train)

In [ ]:
Y_pred=model_knn.predict(X_test)
Y_pred

array([3, 0, 2, 2, 3, 0, 0, 2, 3, 1, 1, 3, 0, 2, 3, 0, 3, 2, 2, 1, 0, 0,
       3, 1, 1, 2, 3, 1, 3, 1, 1, 0, 2, 0, 2, 3, 0, 0, 3, 3, 2, 1, 3, 3,
       1, 3, 0, 1, 3, 1, 1, 3, 0, 3, 0, 3, 2, 2, 0, 3, 3, 1, 3, 2, 1, 2,
       3, 2, 1, 2, 3, 2, 1, 0, 1, 3, 2, 1, 1, 2, 3, 3, 3, 0, 0, 0, 2, 0,
       2, 3, 1, 2, 3, 1, 0, 3, 3, 3, 0, 3, 1, 1, 3, 1, 3, 2, 2, 3, 2, 3,
       3, 0, 0, 1, 3, 3, 0, 1, 1, 0, 0, 3, 2, 2, 1, 1, 1, 1, 0, 2, 1, 3,
       2, 3, 3, 3, 3, 2, 0, 1, 1, 2, 1, 3, 0, 3, 0, 0, 2, 0, 1, 1, 1, 1,
       3, 0, 0, 3, 1, 3, 2, 1, 3, 1, 2, 3, 3, 2, 1, 0, 3, 2, 2, 3, 3, 0,
       2, 2, 3, 0, 2, 1, 0, 1, 3, 1, 2, 0, 2, 3, 1, 1, 0, 2, 3, 0, 1, 3,
       2, 0, 3, 3, 2, 1, 2, 3, 3, 3, 0, 0, 0, 2, 3, 3, 0, 0, 1, 3, 1, 3,
       3, 3, 0, 0, 2, 2, 3, 1, 0, 2, 0, 0, 0, 3, 3, 0, 2, 2, 1, 1, 0, 2,
       3, 3, 0, 0, 1, 3, 3, 2, 3, 0, 3, 1, 1, 0, 2, 3, 3, 2, 0, 0, 1, 2,
       3, 2, 2, 3, 1, 1, 0, 3, 3, 2, 1, 3, 3, 2, 2, 1, 0, 2, 2, 1, 0, 0,
       3, 2, 2, 2, 0, 1, 3, 0, 1, 3, 3, 0, 2, 0, 1,

In [ ]:
from sklearn.metrics import classification_report,accuracy_score,f1_score,confusion_matrix

In [ ]:
knn=accuracy_score(Y_pred,Y_test)
print(classification_report(Y_pred,Y_test))
print(confusion_matrix(Y_pred,Y_test))
knn

              precision    recall  f1-score   support

           0       0.98      0.95      0.97       128
           1       0.92      0.92      0.92       110
           2       0.86      0.90      0.88       119
           3       0.94      0.92      0.93       143

    accuracy                           0.92       500
   macro avg       0.92      0.92      0.92       500
weighted avg       0.93      0.92      0.92       500

[[122   6   0   0]
 [  2 101   7   0]
 [  0   3 107   9]
 [  0   0  11 132]]


0.924